services:
  evolution_api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://localhost:8080
      - DOCKER_RESTART_POLICY=always
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO
      - LOG_COLOR=true
      - STORE_MESSAGES=true
      - STORE_MESSAGE_UP_TO=7
      - CLEAN_STORE_CLEAN_CHAT=true
      - CLEAN_STORE_CLEAN_CONNECTION=true
      - QRCODE_LIMIT=30
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${EVOLUTION_DB_USER}:${EVOLUTION_DB_PASSWORD}@evolution_postgres:5432/${EVOLUTION_DB_NAME}?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_api
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution_redis:6379/6
      - CACHE_REDIS_PREFIX_KEY=evolution
    depends_on:
      - evolution_postgres
      - evolution_redis
    volumes:
      - evolution_instances:/evolution/instances

  evolution_postgres:
    image: postgres:15
    container_name: evolution_postgres
    restart: always
    environment:
      - POSTGRES_DB=${EVOLUTION_DB_NAME}
      - POSTGRES_USER=${EVOLUTION_DB_USER}
      - POSTGRES_PASSWORD=${EVOLUTION_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

  evolution_redis:
    image: redis:latest
    container_name: evolution_redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - evolution_redis_data:/data

  evolution_manager:
    image: evoapicloud/evolution-manager:latest
    container_name: evolution_manager
    restart: always
    ports:
      - "3000:80"
    entrypoint: >
      /bin/sh -c "if [ -f /etc/nginx/conf.d/nginx.conf ]; then sed -i 's/ must-revalidate//g' /etc/nginx/conf.d/nginx.conf; fi && nginx -g 'daemon off;'"

  stayiq_app:
    build: .
    container_name: stayiq_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - evolution_postgres
    env_file:
      - .env
    environment:
      - EVOLUTION_API_URL=http://evolution_api:8080

volumes:
  evolution_instances:
  evolution_postgres_data:
  evolution_redis_data:
